### ISSUE TITLE
why this theme is not in Backdrop CMS Official Website

### ISSUE THREAD

**Issue by domaingood** [backdrop-contrib/radix#30]
why this theme is not in Backdrop CMS Official Website.Also its working with Ver 1.16.1 ?

**Comment by jenlampton** [comment]
In order for a theme to appear inside Backdrop, or on backdropcms.org it needs to have an official release. There are no releases of this theme. It also hasn't been touched since 2016, so it's likely there is a lot that needs to be updated. 

See also: https://github.com/backdrop-contrib/radix/issues/7
